// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlHad1Y8v1TPrgFigaild0RnpoTOqUIM',
    appId: '1:618182370674:web:1fe5fae997ffb7a1e169eb',
    messagingSenderId: '618182370674',
    projectId: 'study-app-608a5',
    authDomain: 'study-app-608a5.firebaseapp.com',
    storageBucket: 'study-app-608a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj5JA19A5h1D1z6b8FZbQCSXUek4EDGPY',
    appId: '1:618182370674:android:8605900a467977c0e169eb',
    messagingSenderId: '618182370674',
    projectId: 'study-app-608a5',
    storageBucket: 'study-app-608a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWy9FfgIpcjkybgRCE6GQO96bYZEvkfao',
    appId: '1:618182370674:ios:2301c69e7c9b3c42e169eb',
    messagingSenderId: '618182370674',
    projectId: 'study-app-608a5',
    storageBucket: 'study-app-608a5.appspot.com',
    iosClientId: '618182370674-mcs1ib56sc962alccbv6s2sqhdige9bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWy9FfgIpcjkybgRCE6GQO96bYZEvkfao',
    appId: '1:618182370674:ios:2301c69e7c9b3c42e169eb',
    messagingSenderId: '618182370674',
    projectId: 'study-app-608a5',
    storageBucket: 'study-app-608a5.appspot.com',
    iosClientId: '618182370674-mcs1ib56sc962alccbv6s2sqhdige9bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStudyApp',
  );
}
